name=TCI by iw7dmh
version=1.0.1
author= Vincenzo Stefanazzi (iw7dmh)
maintainer=
sentence=TCI library for SunSDR rigs
paragraph=See more on https://iw7dmh.jimdofree.com/sunsdr2-pages/tci-esp32s-arduino-libraries/
category=Device Control
url=
architectures=esp32
includes=heltec.h
